config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :movies

  resources :chatrooms, only: :show do
    resources :messages, only: [ :create, :new ]
  end


  resources :foods, only: :show

  resources :pairings, except: :destroy

  get "survey", to: "pages#survey"
  post "otp", to: "pairings#otp"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :pairings, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movie_genres, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/movie.rb
class Movie < ApplicationRecord

  has_many :pairing, dependent: :destroy
  has_many :movie_genres, dependent: :destroy
  has_many :genres, through: :movie_genres

end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :genre
  belongs_to :movie
end

app/models/pairing.rb
class Pairing < ApplicationRecord
  belongs_to :movie
  belongs_to :user
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  def show
    @food = Food.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "messages/message", locals: { message: @message })
      )
      # redirect_to chatroom_path(@chatroom, anchor: "message-#{@message.id}")
    else
      render "chatrooms/show"
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def show
  end

  def new
    # form to enter year and title
    # with this title and year do api call
    # render results of api call into movie partial
    # ajax? insert adjacent html?
    # ask to confirm
    # if no re-render the form
    # if yes Movie.create with the right params from form

  end

  private

  def confirm?
  end
end


# url = "http://www.omdbapi.com/?t=#{@movies.title}&y=#{@movies.year}&apikey=b4c15d98"
#     movie_url = URI.open(url).read
#     movie_json = JSON.parse(movie_url)

#     @title = movie_json["Title"]
#     @plot = movie_json["Plot"]
#     @year = movie_json["Year"]
#     @genre = movie_json["Genre"]
#     @poster = movie_json["Poster"]

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def survey
  end
end

app/controllers/pairings_controller.rb
require 'json'
require 'open-uri'

class PairingsController < ApplicationController
  before_action :set_pairing, only: [:show, :edit, :update, :destroy]

  def index
    @pairings = Pairing.all
  end

  def new
    @pairing = Pairing.new
  end

  def create
    url2 = "https://api.spoonacular.com/recipes/complexSearch?apiKey=e6c9e40f09434dc3963a25a5886a39c9&diet&query=#{params[:pairing][:food]}&number=1"
    food_url = URI.open(url2).read
    food_json = JSON.parse(food_url)

    foodtitle = food_json['results'][0]["title"]
    image = food_json['results'][0]["image"]

    @food = Food.create(dish: foodtitle, image: image)
    @movie = Movie.find(params[:pairing][:movie])
    @pairing = Pairing.new(movie: @movie, food: @food)
    @pairing.user = current_user
    if @pairing.save
      redirect_to pairing_path(@pairing)
    else
      render 'new'
    end
  end

  def show
    @movies = @pairing.movie
    @foods = @pairing.food

    movie_info
  end

  def edit; end

  def update
    @pairing.update(pairing_params)
    redirect_to pairing_path(@pairing)
  end

  def destroy
    @pairing.destroy
    redirect_to pairings_path
  end

  def otp
    @movies = Movie.joins(:genres).select { |movie| movie.genres.map(&:name).any? { |genre| params[:otp].values.include?(genre)} }.uniq
    @movies = @movies.select { |movie| movie.year >= params[:otp][:minyear].to_i && movie.year <= params[:otp][:maxyear].to_i }
    @movies = @movies.sample

    movie_info

    url_2 = "https://api.spoonacular.com/recipes/complexSearch?apiKey=e6c9e40f09434dc3963a25a5886a39c9&diet=#{params[:otp][:diet]}&minCalories=#{params[:otp][:mincalories]}&maxCalories=#{params[:otp][:maxcalories]}&intolerances=#{params[:otp][:intolerances]}&type=mainCourse&number=1"
    url_3 = "https://api.spoonacular.com/recipes/complexSearch?apiKey=e6c9e40f09434dc3963a25a5886a39c9&diet=#{params[:otp][:diet]}&minCalories=#{params[:otp][:mincalories]}&maxCalories=#{params[:otp][:maxcalories]}&type=mainCourse&number=1"
    url_4 = "https://api.spoonacular.com/recipes/complexSearch?apiKey=e6c9e40f09434dc3963a25a5886a39c9&minCalories=#{params[:otp][:mincalories]}&maxCalories=#{params[:otp][:maxcalories]}&intolerances=#{params[:otp][:intolerances]}&type=mainCourse&number=1"
    url_5 = "https://api.spoonacular.com/recipes/complexSearch?apiKey=e6c9e40f09434dc3963a25a5886a39c9&minCalories=#{params[:otp][:mincalories]}&maxCalories=#{params[:otp][:maxcalories]}&type=mainCourse&number=1"
    if params[:otp][:intolerances] != '' && params[:otp][:diet] != ""
      food_url = URI.open(url_2).read
      food_json = JSON.parse(food_url)
    elsif params[:otp][:intolerances] == '' && params[:otp][:diet] != ""
      food_url = URI.open(url_3).read
      food_json = JSON.parse(food_url)
    elsif params[:otp][:diet] == "" && params[:otp][:intolerances] != ''
      food_url = URI.open(url_4).read
      food_json = JSON.parse(food_url)
    else
      food_url = URI.open(url_5).read
      food_json = JSON.parse(food_url)
    end

    foodtitle = food_json['results'][0]["title"]
    image = food_json['results'][0]["image"]
    @foodid = food_json['results'][0]["id"]

    @foods = Food.new(dish: foodtitle, image: image)

    sayings = ["#{@title} with #{foodtitle}, a match made in heaven 😍", "Woah! #{@title} and #{foodtitle}, who'd have thought?! 🧐", "#{@title} and #{foodtitle} FTW 👻", "#{@title} and #{foodtitle}, can't argue with that?!"]
    @saying = sayings.sample
  end

  private

  def set_pairing
    @pairing = Pairing.find(params[:id])
  end

  def pairing_params
    params.require(:pairing).permit(:movie, :food)
  end

  def movie_info
    url = "http://www.omdbapi.com/?t=#{@movies.title}&y=#{@movies.year}&apikey=b4c15d98"
    movie_url = URI.open(url).read
    movie_json = JSON.parse(movie_url)

    @title = movie_json["Title"]
    @plot = movie_json["Plot"]
    @year = movie_json["Year"]
    @genre = movie_json["Genre"]
    @poster = movie_json["Poster"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/chatrooms/show.html.erb
<div class="">
<br>
<br>
<br>

  <h1>#<%= @chatroom.name %></h1>

  <div class="d-flex" id="chatroomdaddy">
  <div class="plex">
    <iframe src="http://127.0.0.1:32400/web/index.html#!/server/ca33fa646bf46c9b4df20fb142df43327c5463d0/details?key=%2Flibrary%2Fmetadata%2F48105" title="Luca" width="1164" height="700" style="border:1px solid black;"></iframe>
    </div>

    <div id="messages" data-chatroom-id="<%= @chatroom.id %>">
      <div class="messages">

          <% @chatroom.messages.each do |message| %>
            <div class="message-container" id="message-<%= message.id %>">

                <p> <font style="color:<%= message.user.color%>"><%= message.user.nickname%></font> : <%= message.content %></p>
                                <%# <small> <%= message.created_at.strftime("%l:%M%p") %>

            </div>
          <% end %>
        </div>
          <%= simple_form_for [ @chatroom, @message ], remote: true do |f| %>
            <%= f.input :content, label: false, placeholder: "Message ##{@chatroom.name}", class: "chat-input"%>
          <% end %>
      </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <!--Popins Thin 100-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital@1&display=swap" rel="stylesheet">
    <!--Popins Medium 500 italic-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@1,400;1,500&display=swap" rel="stylesheet">

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= favicon_link_tag %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message-container" id="message-<%= message.id %>">
  <i class="author">
      <p> <font style="color:<%= message.user.color%>"><%= message.user.nickname%></font> : <%= message.content %> </p>
    <%# <small><%= message.created_at.strftime("%l:%M%p") %>
  </i>
</div>

app/views/movies/new.html.erb
<br>
<br>
<br>
<br>
<br>
<br>

<%= simple_form_for @movies do |f| %>
  <%= f.input :title %>
  <%= ft.integer :year %>
  <%= f.button :submit %>
<% end %>

app/views/movies/show.html.erb
<%= @movie.title %>
<%= @foods.dish %>

app/views/pages/home.html.erb
<div class="scroll-btn">
  <a href="#home"><i class="fas fa-arrow-up"></i></a>
</div>
<div class="banner">
  <div class="banner-container">
    <h1>Can't figure out what to cook and watch on your night in?</h1>
    <p class="tagline"> Don't worry it's simple, choose <h1>Whatever!</h1></p>
    <br>
     <% unless user_signed_in? %>
    <button class="sign-up"><a href="/users/sign_up">Sign up</a></button>
    <% else %>
    <button class="begin"><a> <%= link_to "Begin Journey", survey_path %> </a></button>
    <% end %>
  </div>
</div>

<div class="mood">
  <div class="mood-text">
    <h1>Find the perfect film for your mood! </h1>
    <p class="description"> With our quick and easy survey we'll find you the perfect film for your night in. Simply input your favourite genres then filter movies by release year and we'll make sure to create a perfect match every time.</p>
  </div>

  <div id="carouselExampleSlidesOnly" class="carousel slide carousel-fade" data-ride="carousel" data-interval="3000">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <div class="mood-images" style="background-image: url(<%= image_path 'happy.png' %>)"></div>
      </div>
      <div class="carousel-item">
        <div class="mood-images" style="background-image: url(<%= image_path 'sad.png' %>)"></div>
      </div>
      <div class="carousel-item">
        <div class="mood-images" style="background-image: url(<%= image_path 'angry.png' %>)"></div>
      </div>
    </div>
  </div>
</div>


<div class="food">
  <div id="carouselExampleSlidesOnly" class="carousel slide carousel-fade" data-ride="carousel" data-interval="3000">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <div class="mood-images" style="background-image: url(<%= image_path 'food.png' %>)"></div>
      </div>
      <div class="carousel-item">
        <div class="mood-images" style="background-image: url(<%= image_path 'food2.png' %>)"></div>
      </div>
      <div class="carousel-item">
        <div class="mood-images" style="background-image: url(<%= image_path 'food3.png' %>)"></div>
      </div>
    </div>
  </div>
    <div class="food-text">
      <h1>Fridge full of food, but no idea what to make?</h1>
      <p>Whatever has got you covered- we will provide you with a custom generated meal to cook which pairs with the movie you are watching. Don't like the choice, or missing some ingredients? No need to worry- browse our community pairings for inspiration. </p>
    </div>
  </div>
</div>

<div class="footer">
  <p><a href="https://twitter.com/watch_whatever"><i class="fab fa-twitter-square"></i></a></p>
  <p><span class="smaller">© 2021 Whatever, Inc.</span></p>
</div>

app/views/pages/survey.html.erb
<br>
<br>
<br>
<br>
<div class="bannerimage"></div>
<div class="container">

  <h1 class="survey-title">Welcome to your movie finding journey!</h1>
  <h3 class="survey-header">1. Select your favourite movie genres <i class="fas fa-hand-pointer"></i><br></h3>
  <h3 class="survey-header"><i class="fas fa-angle-double-down" style="margin-bottom: 25px;"></i></h3>
  <%= form_for :otp , url:otp_path do |f| %>
  <div class="genres">
    <%= f.check_box :Fantasy, {class: 'checkbox fantasy'}, 'Fantasy', false %>
    <%= f.label :Fantasy %>
    <%= f.check_box :Thriller, {class: 'checkbox thriller'}, 'Thriller', false  %>
    <%= f.label :Thriller %>
    <%= f.check_box :crime , {class: 'checkbox crime'}, 'Crime', false %>
    <%= f.label :crime %>
    <%= f.check_box :War, {class: 'checkbox war'}, 'War', false  %>
    <%= f.label :War %>
    <%= f.check_box :Action, {class: 'checkbox action'}, 'Action', false  %>
    <%= f.label :Action %>
    <%= f.check_box :Biography, {class: 'checkbox biography'}, 'Biography', false  %>
    <%= f.label :Biography %>
    <%= f.check_box :Adventure, {class: 'checkbox adventure'}, 'Adventure', false  %>
    <%= f.label :Adventure %>
    <%= f.check_box :History, {class: 'checkbox history'}, 'History', false  %>
    <%= f.label :History %>
    <%= f.check_box :SciFi, {class: 'checkbox scifi'}, 'Sci-Fi', false  %>
    <%= f.label :SciFi %>
    <%= f.check_box :Romance, {class: 'checkbox romance'}, 'Romance', false  %>
    <%= f.label :Romance %>
    <%= f.check_box :Western, {class: 'checkbox western'}, 'Western', false  %>
    <%= f.label :Western %>
    <%= f.check_box :Comedy, {class: 'checkbox comedy'}, 'Comedy', false  %>
    <%= f.label :Comedy %>
    <%= f.check_box :Animation, {class: 'checkbox animation'}, 'Animation', false  %>
    <%= f.label :Animation %>
    <%= f.check_box :Family, {class: 'checkbox family'}, 'Family', false  %>
    <%= f.label :Family %>
    <%= f.check_box :Mystery, {class: 'checkbox mystery'}, 'Mystery', false  %>
    <%= f.label :Mystery %>
    <%= f.check_box :Music, {class: 'checkbox music'}, 'Music', false  %>
    <%= f.label :Music %>
    <%= f.check_box :Horror, {class: 'checkbox horror'}, 'Horror', false  %>
    <%= f.label :Horror %>
    <%= f.check_box :FilmNoir, {class: 'checkbox filmnoir'}, 'Film-Noir', false  %>
    <%= f.label :FilmNoir %>
  </div>
  <div class="slider-container">

    <h3 class="survey-header">2. Filter movies based on release year <i class="fas fa-sliders-h" style="margin-top: 20px;margin-bottom: 30px;"></i></h3>

    <div class="multi-range-slider" style="margin-bottom: 100px;">
      <input type="range" id="minyear" min="1930" max="2021" value="1930" name="otp[minyear]">
      <input type="range" id="maxyear" min="1930" max="2021" value="2021" name="otp[maxyear]">

      <div class="slider">
        <div class="track"></div>
        <div class="range"></div>
        <div class="thumb left"></div>
        <div class="thumb right"></div>
      </div>
      <div class="output1">
        <output id="output1"></output>
      </div>
      <div class="output2">
        <output id="output2"></output>
      </div>
    </div>

    <h3 class="survey-header">3. Filter food based on amount of calories <i class="fas fa-sliders-h" style="margin-top: 20px;margin-bottom: 30px;"></i></h3>

    <div class="calories" style="margin-top: 20px;">
	    <div class="multi-range-slider">
      <input type="range" id="mincalories" min="300" max="2000" value="300" name="otp[mincalories]">
      <input type="range" id="maxcalories" min="300" max="2000" value="2000" name="otp[maxcalories]">

      <div class="calories-slider">
        <div class="calories-track"></div>
        <div class="calories-range"></div>
        <div class="calories-thumb calories-left"></div>
        <div class="calories-thumb calories-right"></div>
      </div>
      <div class="calories1">
        <output id="calories1"></output>
      </div>
      <div class="calories2">
        <output id="calories2"></output>
      </div>
    </div>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
 <div class="container">
 <h3 class="survey-header">4. Filter food based on diet and intolerances <i class="fas fa-sort"></i></h3>
 <br>
  <span style="font-size: 20px;"> <%= f.label :diet %> </span>
  <%= f.select :diet, ["", "Gluten Free", "Ketogenic", "Vegetarian", "Lacto-Vegetarian", "Ovo-Vegetarian", "Vegan", "Pescetarian", 'Paleo', 'Primal', 'Whole30']%>
  <br>
  <span style="font-size: 20px;"> <%= f.label :intolerances  %> </span>
  <%= f.select :intolerances, ["",'Dairy', 'Egg', 'Gluten', 'Grain', 'Peanut', 'Seafood', 'Sesame', 'Shellfish', 'Soy', 'Sulfite', 'Tree Nut', 'Wheat'] %>
 </div>
 <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <div class="buttoncontainer">
    <%= button_tag do %>
      <a class="bigredbutton"></a>

    <% end %>


  <% end %>
</div>

</div>

<div style="width: 100vw; margin-top: 50px;" class="footer">
  <p><a href="https://twitter.com/watch_whatever"><i class="fab fa-twitter-square"></i></a></p>
  <p><span class="smaller">© 2021 Whatever, Inc.</span></p>
</div>

app/views/pairings/index.html.erb
<div class="body1">
  <br>
  <br>
  <br>
  <br>
  <div>
    <h1>Pairings</h1>
  </div>
  <div class="pairing-daddy-container">
    <div>
      <%= link_to "Create a new pairing", new_pairing_path, class: "sign-up new-pairing-button" %>
    </div>
    <div class="pairings-container">
    <% @pairings.each do |pairing|%>
      <div class="pairings-card">
        <p class="name"> <%= pairing.movie.title %> </p>
        <p class="name"> <%= pairing.food.dish %> </p>
        <button class="button"><%= link_to "View Pairing", pairing_path(pairing), class: "sign-up" %></button>
      </div>
      <% end %>
    </div>
  </div>

</div>

<div class="footer">
  <p><a href="https://twitter.com/watch_whatever"><i class="fab fa-twitter-square"></i></a></p>
  <p><span class="smaller">© 2021 Whatever, Inc.</span></p>
</div>

app/views/pairings/new.html.erb
<div class="body1">
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <div class="container">

  <%= simple_form_for @pairing do |f| %>
    <%= f.input :movie, collection: Movie.all, input_html: { class: 'select2', autofocus: true  } %>
    <%= f.input :food %>
    <%= f.button :button, type: :submit, class: 'sign-up pairbutton' do %>
      <span>Create pairing</span>
    <% end %>
  <% end %>
  </div>

</div>

app/views/pairings/otp.html.erb
<br>
<br>
<br>
<br>
<h2 style="text-align: center; color: #f8f7f2; text-shadow: 2px 2px #810000; font-size: 50px;">It's a match!</h2>
<div class="pairings_container" style="display: flex; justify-content: center; margin-top: 50px;">
  <%= render 'shared/moviecard' %>
  <div style="zindex: 3; align-self: center;">

    <%= image_tag 'movie-food-connectersrgb2.png' %>

    <p class="saying" style="margin: 0 auto; margin-top: 75px; width: 350px; color: #f8f7f2;"><%=@saying%></p>

  </div>
  <%= render 'shared/foodcard' %>
</div>

    <div class="container"><%= link_to "Movie ChatRoom", 'https://www.whatever.watch/chatrooms/7', class: "sign-up m-1", style:"text-decoration: none;" %></div>
    <br>

    <div class="container"><%= link_to "Back to quiz", survey_path, class: "sign-up m-1", style:"text-decoration: none;" %></div>


<div style="margin-top: 50px"; class="footer">
  <p><a href="https://twitter.com/watch_whatever"><i class="fab fa-twitter-square"></i></a></p>
  <p><span class="smaller">© 2021 Whatever, Inc.</span></p>
</div>

app/views/pairings/show.html.erb
  <br>
  <br>
  <br>
  <br>
  <br>


  <div class="pairings_container" style="display: flex; justify-content: center; margin-top: 50px;">
  <%= render 'shared/moviecard' %>
  <div style="zindex: 3; align-self: center;">

    <%= image_tag 'movie-food-connectersrgb2.png' %>

  </div>
  <%= render 'shared/foodcard' %>

</div>
<br>
<div class="back-button">
  <%= link_to "Back to pairings", pairings_path, class: "sign-up back-pairings" %>
</div>
<br>
<br>
<br>
<br>
<div class="footer">
  <p><a href="https://twitter.com/watch_whatever"><i class="fab fa-twitter-square"></i></a></p>
  <p><span class="smaller">© 2021 Whatever, Inc.</span></p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_foodcard.html.erb
  <% result = @foods.dish.gsub(" ", "-")%>
<div class="food-card">
  <div class="scene">
    <div class="food_card">
      <div class="card__face card__face--back">
        <div class="food-card-back">
          <%= link_to "https://spoonacular.com/recipes/#{result}-#{@foodid}", target: "_blank" do %>
            <h2><%= @foods.dish %></h2>
          <% end %>
        </div>
      </div>
      <div class="card__face card__face--front">
        <%= link_to "https://spoonacular.com/recipes/#{result}-#{@foodid}", target: "_blank" do %>
          <img src=<%="#{@foods.image}"%> alt="movie poster" class="food-image">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_moviecard.html.erb
<div class="movie-card" id="results">
  <div class="scene">
    <div class="movie_card">
      <div class="card__face card__face--back">
        <div class="movie-card-back">
          <a href="http://127.0.0.1:32400/web/index.html#!/server/ca33fa646bf46c9b4df20fb142df43327c5463d0/details?key=%2Flibrary%2Fmetadata%2F48105" target="_blank">
            <h2> <%= @movies.title %> (<%= @year %>)</h2>
            <p> <%= @genre %> </p>
            <p> <%= @plot %> </p>
          </a>
        </div>
      </div>
      <div class="card__face card__face--front">
        <a href="http://127.0.0.1:32400/web/index.html#!/server/ca33fa646bf46c9b4df20fb142df43327c5463d0/details?key=%2Flibrary%2Fmetadata%2F48105" target="_blank">
          <img src="<%= @poster%>"  alt="movie poster">
        </a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag("logo.png") %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "popcorn.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Pairings", pairings_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>